language: java
jdk:
- oraclejdk8
env:
  matrix:
  - MYVAR="ONE"
  - MYVAR="TWO"  secure:rxo5zvK6lul/hEDGqwRMlz4BCRJIRofuZch3U6UQHMOBRUS+5mJ828YDQdEPS/cCLgXNBOi+jtSr9gtv2L407LrPqgrH4zBt3My5D9dRNJBtxWOvXMpPHqyX7CFTIq+mJFnrYE/UY5GGjOLGiYnBAJsak5YUWUURmX0FPH7X5j12ZZNp9OLK4sScRZZoaXKNv8KeInALXH7jQYDn3ZaMDmDizfic/1TN+B+YciB3JXns9uvB+as94+nSgfWqbc0rn5qYQqUELGR2MwFZCDUGuV7r6TgzAn2+foEgXZj4JgbeNWH1U+ZY5lHeU+auzs/ANYNEJ5Xp7dp5CpkO5DIplA66VY75TwDuV1laF3nFZrdz/iJOlzkaYCsxvVvAgofcvXjsw+12jCiQzlD5/oKCD27g+rXzMw4HOQcwNDdzZfECWsiSKrE13Y5kYhcloC8pW4gSv2mv19aT3fXTXlkaZSjobYnnOjpJvTbsS/A5hyXFHN/6gLb71QQWU+ZErSlL0xkK6DyTtxum8CGfKCJSnCWZVGx7OOtym0RhLigLCEV7Fe9ej+uZ59dT00gWtjniVWPGEfOgSsDZUhBHZhy312WUhQWV6Lj2Qifk4WOOCBO3nAFsz62vW/TOzS4xLZ2GhQ7KAwnu9LW8XoHU+nt/ape+rtGkhYTDVo2CwMEDefY=
