language: java
jdk:
- oraclejdk8
env:
    matrix:
    - MYVAR="ONE"  BAZ="naaa"
    - MYVAR="TWO"
     secure: dCjoubrrDsYYS/+RI/W4ICSDd0xrfufm6WN3Z+jeIplMq3TZszkf0WfC//wwQ8MZwjLOm73sKg4c+49B8u31ON9Dc/45a7JDulhMA1SDS7VWie7PdG/Vrxf6eflTrimHjaAayyyegwCWT53ivkeogZLRKoVqDzd2/a3r9uP1auRzQud5SJ3XqdsZ9zk1zFkdetFpwtAMEV26hQSKFC36FtD+WsznuFg6GKXAW2xNXX4G+wm/F3b9POHFGyHSlVe1SboKrFBq2EvqhyhHJqp6+P++s3WauHMc3tdLgCL1mkUT/OEwS7htMs0QpSjQ839Z6IywXl8kn3F8UWDep0Uu5pPKSxe3TW0p0UlyyALtkfZ2dUjawIbSLfjg0TTaynnswBNSPMHrOPR4PqYG/Z9F1H1wt9nzeTdG3NRJvrdOx2wDaSsFCAxfB/Jzq/8ynzf1KVFzIPLQOd9DbsP4rWxpVTn6tEFgol3xkB+/JKk/YOLn6dszTtA7Pan5y8MEqF1z+Mv6Lc7QQxJVNylVLNdAJn/jCq0URkAjBODFZ1B4ddtfnM3FSoaJ/LZG/C/3TKgq6B14LaId8ZLt9IWV9th4J9h4I/qukoHIZcMjNVppfCOh6KmXkjPCaEcRmyaRcxZHu88pK+hwEVEKaTGTAH+brNv7Zg+EtzoHvRFlT+O0n+I=
